### ISSUE TITLE
Unsure why modularization broke Mongoose Assignment

### ISSUE THREAD

**Issue by SalvatoreSantamaria** [CodingDojo-MEAN-01-19/SamS#3]
https://github.com/CodingDojo-MEAN-01-19/SamS/blob/05590874b0749de1d1905ccb2338e2bcd806d021/04-mongodb/02-mongoose/02-mongoose-dashboard%20-%20Copy/server.js#L1-L123

I'm continually getting these error messages:
POST DATA undefined
TypeError: Cannot read property 'name' of undefined

I also can't figure out why I can't modularize my model. 

Can you help?

**Comment by dojo-json** [comment]
If you recall the lecture concerning middleware it was determined that order matters. Consider when you are creating your routes and where you assign middleware, such as body-parser.

**Comment by SalvatoreSantamaria** [comment]
Ah, thanks. Solved it! :D
