### ISSUE TITLE
Issue with Rendering the comments of messages

### ISSUE THREAD

**Issue by SalvatoreSantamaria** [CodingDojo-MEAN-01-19/SamS#4]
https://github.com/CodingDojo-MEAN-01-19/SamS/blob/bd9216265e84463f38046d131a3f7f0d90093ca4/04-mongodb/02-mongoose/03-message-board/views/index.ejs#L37-L41

Hey Jason, help!, 

Either I'm trying to put the comments in index.ejs, or doing something wrong with how I'm entering the comment into the database. 

I spent FAR to much time on this project... :(

**Comment by dojo-json** [comment]
It appears you are trying to iterate over `user.message` which is a string, rather than `user.comment` which is an array of comment object ids.

**Comment by SalvatoreSantamaria** [comment]
I fixed that, still no luck- I'd like to try to complete during our meeting today: https://github.com/CodingDojo-MEAN-01-19/SamS/tree/master/04-mongodb/02-mongoose/03-message-board

**Comment by SalvatoreSantamaria** [comment]
Thanks for your help @dojo-json !!! Closing
